lang: "en"
timezone: "Europe/Amsterdam"
title: "Nick Been"

exclude:
  - package*.json
  - serviceworker.ts
  - tailwind.config.js
  - workbox-config.js

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
